config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
  end

  mount Sidekiq::Web => '/sidekiq'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  # if routing the root path, update for your controller
  root to: 'pages#show', id: 'home'

  get 'users/index'
  # match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :dashboard, only: [:index]

  namespace :api do
    namespace :v1, defaults: { format: 'json' } do
      # Testing endpoint for authentication
      get '/test' => 'base#test' if Rails.env.test?
      post '/token' => 'base#token'

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/sessions',
      }

      resources :promotional_tweets, only: [:index, :create]
      resources :subscriptions, only: [:create, :update] do
        post '/cancel' => 'subscriptions#cancel', on: :member
      end
      resources :subscription_plans, only: [:index]
      resources :invoices, only: [:index]
      resources :listen_signals, only: [:index, :show, :create, :update, :destroy] do
        get :templates, on: :collection
      end
      resources :users, only: [] do
        get '/me' => 'users#show', on: :collection
        post :update, on: :member
      end
      resources :brands, only: [:destroy] do
        get '/me' => 'brands#show', on: :collection
        get '/account_plans' => 'brands#account_plans', on: :collection
        post '/account_info' => 'brands#update_account_info', on: :collection
      end
    end
  end

  namespace :webhooks do
    namespace :stripe, defaults: { format: 'json' } do
      post '/' => 'base#index'
    end
  end

  get 'subscription_plans' => 'dashboard#index', as: :subscription_plans
  get 'finish_setup' => 'dashboard#index', as: :finish_setup

  # Catch all for any routes nested with `/dashboard`. Any non-existant routes will be handled by the React app.
  get 'dashboard/*other' => 'dashboard#index'

  # Catch all for High Voltage static page thingy
  get "/*id" => 'pages#show', as: :page, format: false
end

app/views/shared/_footer.html.haml
%footer.footer
  .container-fluid
    .footer-items
      %span
        = link_to(image_tag('logo/signalplus-icon.png', :alt => 'SignalPlus +', height:'31', width:'47', class: 'footer-brand'), root_url)
      = link_to 'CONTACT', page_path(id: 'support'), class: 'footer-link'
      |
      = link_to 'PRIVACY POLICY', page_path(id: 'privacy'), class: 'footer-link'
      |
      = link_to 'TERMS OF USE', page_path(id: 'agreement'), class: 'footer-link'
      %span.footer-site-inc SignalPlus Inc / All Rights Reserved

app/views/shared/_header.html.haml
%nav.navbar.navbar-static-top{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to(image_tag('logo/signalplus-pink.png', :alt => 'SignalPlus +', width:'140', height:'20'), root_url, class: 'navbar-brand')
    / Collection of nav links and other content for toggling
    #navbarCollapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'SUPPORT', page_path(id: 'support')
        - path = current_user ? dashboard_index_path : new_user_session_path
        - link_text = current_user ? 'DASHBOARD' : 'LOG IN'
        %li= link_to link_text, path, class: 'header-cta'